# Generated by Django 4.0.3 on 2022-06-05 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid_Trasaction',
            new_name='BidTransaction',
        ),
    ]
