# Generated by Django 3.2.4 on 2022-06-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20220609_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='verified_by_user',
        ),
    ]
