# Generated by Django 3.2.4 on 2022-06-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_remove_product_verified_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='verified_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
