# Generated by Django 3.2.4 on 2022-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20220609_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proposed_minimum_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
