# Generated by Django 3.2.4 on 2022-06-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_product_proposed_minimum_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bid_expiry',
        ),
        migrations.AddField(
            model_name='product',
            name='bid_duration',
            field=models.TimeField(default='00:30'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_start',
            field=models.DateTimeField(null=True),
        ),
    ]
