# Generated by Django 3.2.4 on 2022-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20220614_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bid_duration',
        ),
        migrations.AddField(
            model_name='product',
            name='bid_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
