# Generated by Django 3.2.4 on 2022-06-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20220614_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
