# Generated by Django 3.2.4 on 2022-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
