# Generated by Django 3.2.4 on 2022-06-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
