# Generated by Django 3.2.4 on 2022-06-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_product_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ended',
        ),
    ]
