# Generated by Django 3.2.4 on 2022-06-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_remove_product_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
