# Generated by Django 3.2.4 on 2022-06-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_auction_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='maximum_bid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
