# Generated by Django 4.1 on 2022-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auction_maximum_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='varified_by',
            new_name='verified_by',
        ),
        migrations.AlterField(
            model_name='bidtransaction',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
    ]
