# Generated by Django 4.1 on 2022-09-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_rename_varified_by_product_verified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='min_required_credit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
