# Generated by Django 4.1 on 2022-09-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0022_remove_auction_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='auction',
            name='min_required_credit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
