# Generated by Django 4.1 on 2022-09-24 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0024_product_is_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_varified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
