# Generated by Django 4.1 on 2022-09-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_alter_auction_verified_by_alter_product_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='auction',
            name='is_varified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_varified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
