# Generated by Django 3.2.4 on 2022-06-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='default.jpg', upload_to='profiles'),
        ),
    ]
