# Generated by Django 4.1 on 2022-09-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='varified_by',
            new_name='verified_by',
        ),
    ]
