# Generated by Django 4.1 on 2022-09-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_varified_by_profile_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verfication_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
