# Generated by Django 4.1 on 2022-09-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_verfication_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_varified',
            field=models.BooleanField(null=True),
        ),
    ]
