# Generated by Django 4.1 on 2022-09-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_is_varified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('rasel', 'Rasel'), ('shihab', 'Shihab'), ('sharmin', 'Sharmin')], max_length=200, null=True),
        ),
    ]
