# Generated by Django 4.1 on 2022-09-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_varified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
